<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBUcLL5w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBUcLL5w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBUcLL5w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBUcLL5w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBUcLL5w\App_KernelDevDebugContainer([
    'container.build_hash' => 'BUcLL5w',
    'container.build_id' => '8cc61b23',
    'container.build_time' => 1606501912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBUcLL5w');
