<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'smartphone_index' => [[], ['_controller' => 'App\\Controller\\SmartphoneController::index'], [], [['text', '/smartphone/']], [], []],
    'find_smartphone_by_name' => [['name'], ['_controller' => 'App\\Controller\\SmartphoneController::findAllByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/smartphone']], [], []],
    'smartphone_new' => [[], ['_controller' => 'App\\Controller\\SmartphoneController::new'], [], [['text', '/smartphone/new/create']], [], []],
    'smartphone_show' => [['id'], ['_controller' => 'App\\Controller\\SmartphoneController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/smartphone/details']], [], []],
    'smartphone_edit' => [['id'], ['_controller' => 'App\\Controller\\SmartphoneController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/smartphone']], [], []],
    'smartphone_delete' => [['id'], ['_controller' => 'App\\Controller\\SmartphoneController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/smartphone/delete']], [], []],
    'type_index' => [[], ['_controller' => 'App\\Controller\\TypeController::index'], [], [['text', '/type/']], [], []],
    'type_new' => [[], ['_controller' => 'App\\Controller\\TypeController::new'], [], [['text', '/type/new']], [], []],
    'type_show' => [['id'], ['_controller' => 'App\\Controller\\TypeController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/type']], [], []],
    'type_edit' => [['id'], ['_controller' => 'App\\Controller\\TypeController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/type']], [], []],
    'type_delete' => [['id'], ['_controller' => 'App\\Controller\\TypeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/type']], [], []],
];
