<?php

namespace Container8Ki0HvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQVyWLGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nQVyWLG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nQVyWLG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'smartphone' => ['privates', '.errored..service_locator.nQVyWLG.App\\Entity\\Smartphone', NULL, 'Cannot autowire service ".service_locator.nQVyWLG": it references class "App\\Entity\\Smartphone" but no such service exists.'],
        ], [
            'smartphone' => 'App\\Entity\\Smartphone',
        ]);
    }
}
