<?php

namespace Container8Ki0HvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R_CXpkUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R.CXpkU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R.CXpkU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'smartphoneRepository' => ['privates', 'App\\Repository\\SmartphoneRepository', 'getSmartphoneRepositoryService', true],
        ], [
            'smartphoneRepository' => 'App\\Repository\\SmartphoneRepository',
        ]);
    }
}
