<?php

namespace Container8Ki0HvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmartphoneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nQVyWLG.App\Entity\Smartphone' shared service.
     *
     * @return \App\Entity\Smartphone
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nQVyWLG": it references class "App\\Entity\\Smartphone" but no such service exists.');
    }
}
