<?php

namespace Container8Ki0HvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AVQA72y.App\Entity\Type' shared service.
     *
     * @return \App\Entity\Type
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.AVQA72y": it references class "App\\Entity\\Type" but no such service exists.');
    }
}
