<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4K19Xl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4K19Xl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG4K19Xl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG4K19Xl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG4K19Xl\App_KernelDevDebugContainer([
    'container.build_hash' => 'G4K19Xl',
    'container.build_id' => '01b76171',
    'container.build_time' => 1604355547,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG4K19Xl');
